export const REDIS_CLIENT_PROVIDER = 'REDIS_CLIENT_PROVIDER';
export const REDIS_CLIENT_URI = 'REDIS_CLIENT_URL';
export const WEB_SOCKET_PROVIDER = 'WEB_SOCKET_PROVIDER';
export const WEB_SOCKET_URI = 'WEB_SOCKET_URL';
export const REDIS_HASH_KEY = 'REDIS_HASH_KEY';
export const MESSAGE_CHANNEL = 'message';
